import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import ClientWrapper from "./components/ClientWrapper";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react"; // Import SessionProvider from NextAuth.js

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Provide the client to your App */}

          <ClientWrapper> 
            {children}
            <Toaster />
          </ClientWrapper>
       
      </body>
    </html>
  );
}
